


### Security Requests



###
GET /api/v1/security/csrf-token
Host: localhost:9000
Accept: application/json



### Identity Requests



###
POST /api/v1/identities/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
X-Csrf-Token: fdaipyh5syL0RGDksHyzW1DSNWRckXFNX0ekB_dVk1PK38_fTO6TwR5K0UDZclaC1FGHamnhGAY-pxJgPn7BMMZloGOv6Pzs

{
    "authority": "ADMIN",
    "username": "burgasvv",
    "password": "burgasvv",
    "email": "burgasvv@gmail.com",
    "status": true,
    "firstname": "Бургас",
    "lastname": "Вячеслав",
    "patronymic": "Васильевич"
}

###
POST /api/v1/identities/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
X-Csrf-Token: UkMsu3tHfM_fNrdtR1JNo2Sg7z0gdAtcMXuP2kpaXUrmi94oZHRI3hgjGq3yUNRcfn95lgaTwlwTQGlxVBnp4ys_anKE6bgb

{
    "authority": "USER",
    "username": "zagor",
    "password": "zagor",
    "email": "zagor@gmail.com",
    "status": true,
    "firstname": "Загорулько",
    "lastname": "Борис",
    "patronymic": "Юрьевич"
}

###
POST /api/v1/identities/update
Host: localhost:9000
Accept: application/json
Content-Type: application/json
X-Csrf-Token: UkMsu3tHfM_fNrdtR1JNo2Sg7z0gdAtcMXuP2kpaXUrmi94oZHRI3hgjGq3yUNRcfn95lgaTwlwTQGlxVBnp4ys_anKE6bgb
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "id": "060f883f-09e6-4cde-9a75-5f34447d2264",
    "username": "burgasvv"
}

###
GET /api/v1/identities
Host: localhost:9000
Accept: application/json

###
GET /api/v1/identities/by-id?identityId=060f883f-09e6-4cde-9a75-5f34447d2264
Host: localhost:9000
Accept: application/json

###
DELETE /api/v1/identities/delete?identityId=94b47fdb-1f67-412e-b652-b320b067b2eb
Host: localhost:9000



### Identity-Image Requests



###
PUT /api/v1/identity-images/make-preview
Host: localhost:9000
Accept: application/json
Content-Type: application/json
X-Csrf-Token: CYY5FCjnX5GpIFv32Z1SeKwO_ameP3CpMygFKBwfYBvQ_W2oP7FdcUuDOfOERjjG4LBmTc490MitCxKEVkpjEX16VyOynwub
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "entityId": "060f883f-09e6-4cde-9a75-5f34447d2264",
    "imageId": "5e5652ee-7a2b-4639-97ed-6ce321888cf9"
}

###
DELETE /api/v1/identity-images/delete?identityId=060f883f-09e6-4cde-9a75-5f34447d2264
Host: localhost:9000
Accept: application/json
Content-Type: application/json
X-Csrf-Token: xDgQGsT2B3JtMSWfhiffinVP-bl-ml4jwzHWgax7zoiz4BAP8g90f6eSYRBAV0auvwrrvxd81NhNrjwOplOwuM0e-bDRgnY8
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "documentIds": ["7013c56d-6be4-4123-9878-0940beb6d726"]
}

###
GET /api/v1/identity-images/by-id?imageId=422998fd-470c-4fdf-b5fd-e308a242d361
Host: localhost:9000
Accept: application/json



### Chat Requests



###
POST /api/v1/chats/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
X-Csrf-Token: fdaipyh5syL0RGDksHyzW1DSNWRckXFNX0ekB_dVk1PK38_fTO6TwR5K0UDZclaC1FGHamnhGAY-pxJgPn7BMMZloGOv6Pzs
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "name": "New Attractive",
    "description": "Описание чата New Attractive Chat",
    "adminId": "48fd24e7-17db-4abc-8cb9-bf261d5127a8"
}

###
POST /api/v1/chats/update
Host: localhost:9000
Accept: application/json
Content-Type: application/json
X-Csrf-Token: H4GsHPn9Fy3wHCsPRciwtOdiryi8CN0O5sqNeGf3FKYWH6xnKbbIeZqZcU_dekg-fOWEgYVRgkmPPL8jg6jrQQaSI550fcpU
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "id": "9e048b8d-9f19-43f5-9e41-83cafd094dfc",
    "name": "New Attractive Chat",
    "adminId": "3471ddd1-fd94-4f80-b556-6f5c88d3cdd5"
}

###
PUT /api/v1/chats/join
Host: localhost:9000
Accept: application/json
Content-Type: application/json
X-Csrf-Token: DGXnPDmhftMvWhcnC9i3e5lxTstid-eQ9FugNSGOWBq7RO9XOlKDWVrFGLECPHQWMvWDTvtCY6pRQ4W9kTnGDEDrbyLZJolk
Authorization: Basic zagor@gmail.com zagor

{
    "groupId": "9e048b8d-9f19-43f5-9e41-83cafd094dfc",
    "applicantId": "3471ddd1-fd94-4f80-b556-6f5c88d3cdd5"
}

###
PUT /api/v1/chats/out
Host: localhost:9000
Accept: application/json
Content-Type: application/json
X-Csrf-Token: DGXnPDmhftMvWhcnC9i3e5lxTstid-eQ9FugNSGOWBq7RO9XOlKDWVrFGLECPHQWMvWDTvtCY6pRQ4W9kTnGDEDrbyLZJolk
Authorization: Basic zagor@gmail.com zagor

{
    "groupId": "9e048b8d-9f19-43f5-9e41-83cafd094dfc",
    "applicantId": "3471ddd1-fd94-4f80-b556-6f5c88d3cdd5"
}

###
GET /api/v1/chats/by-id?chatId=9e048b8d-9f19-43f5-9e41-83cafd094dfc
Host: localhost:9000
Accept: application/json