
server:
  port: 9000
spring:
  application:
    name: talker-java
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5000/talker_java_db'
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 300000
      max-lifetime: 1200000
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
  liquibase:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5000/talker_java_db'
    user: postgres
    password: postgres
  data:
    redis:
      host: localhost
      port: 6000
  servlet:
    multipart:
      max-file-size: 10000000
      max-request-size: 1000000000
logging:
  level:
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.hibernate.transaction: DEBUG